import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

const baseUrl = "https://tinyops.dev";

export const metadata: Metadata = {
  title: { default: "TinyOps | CI/CD Prompt Library", template: "%s | TinyOps" },
  description: "Production-grade CI/CD workflows for Vercel + GitHub Actions, generated by AI. Browse our curated collection of battle-tested prompts and ship faster.",
  metadataBase: new URL(baseUrl),
  alternates: { canonical: baseUrl, types: { "application/rss+xml": `${baseUrl}/rss.xml` } },
  keywords: ["CI/CD","GitHub Actions","Vercel","DevOps","Automation","Workflows","AI Prompts","Deployment","Testing","Developer Tools","TinyOps"],
  authors: [{ name: "TinyOps" }],
  creator: "TinyOps",
  publisher: "TinyOps",
  robots: { index: true, follow: true, googleBot: { index: true, follow: true, "max-video-preview": -1, "max-image-preview": "large", "max-snippet": -1 } },
  openGraph: { type: "website", locale: "en_US", url: baseUrl, title: "TinyOps | CI/CD Prompt Library", description: "Production-grade CI/CD workflows for Vercel + GitHub Actions, generated by AI.", siteName: "TinyOps", images: [{ url: `${baseUrl}/og-image.png`, width: 1200, height: 630, alt: "TinyOps - CI/CD Prompt Library" }] },
  twitter: { card: "summary_large_image", title: "TinyOps | CI/CD Prompt Library", description: "Production-grade CI/CD workflows for Vercel + GitHub Actions, generated by AI.", images: [`${baseUrl}/og-image.png`], creator: "@tinyops" },
  icons: { icon: "/favicon.svg", shortcut: "/favicon.svg", apple: "/apple-touch-icon.svg" },
  manifest: `${baseUrl}/site.webmanifest`,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;600;700;800;900&display=swap" />
      </head>
      <body className="bg-[#EDEBE7] text-neutral-900 min-h-screen antialiased font-sans">
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            style: { background: "#fff", border: "1px solid #e5e5e5", color: "#0a0a0a", borderRadius: "12px" },
            className: "font-sans shadow-lg",
          }}
        />
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
