import { getAllPrompts } from '@/lib/mdx';
import { NextResponse } from 'next/server';

export async function GET() {
  const prompts = getAllPrompts();
  const baseUrl = 'https://tinyops.dev';

  const rss = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>TinyOps - CI/CD Prompt Library</title>
    <link>${baseUrl}</link>
    <description>Production-grade Vercel + GitHub Actions workflows, generated by AI. Browse our curated collection of battle-tested CI/CD prompts.</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="${baseUrl}/rss.xml" rel="self" type="application/rss+xml" />
    <image>
      <url>${baseUrl}/og-image.png</url>
      <title>TinyOps - CI/CD Prompt Library</title>
      <link>${baseUrl}</link>
    </image>
    ${prompts
      .map(
        (prompt) => `
    <item>
      <title><![CDATA[${prompt.title}]]></title>
      <link>${baseUrl}/prompt/${prompt.slug}</link>
      <guid isPermaLink="true">${baseUrl}/prompt/${prompt.slug}</guid>
      <description><![CDATA[${prompt.description}]]></description>
      <category>${prompt.category}</category>
      ${prompt.tags.map((tag) => `<category><![CDATA[${tag}]]></category>`).join('\n      ')}
      <pubDate>${new Date(prompt.date).toUTCString()}</pubDate>
    </item>`
      )
      .join('')}
  </channel>
</rss>`;

  return new NextResponse(rss, {
    headers: {
      'Content-Type': 'application/xml',
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
    },
  });
}